### ISSUE TITLE
DF delete specific file

### ISSUE THREAD

**Issue by smaletho** [r1pper/GoPro.Hero#13]
Hey @r1pper,

Whats the url syntax for the camera/DF command? How do you specify the file?

From what I could gather, it looked something like 10.5.5.9/camera/DF?t=1234&p=%15

Any help would be greatly appreciated.

-Tom

**Comment by r1pper** [comment]
Hi @smaletho 

here is an example of the command `http://10.5.5.9/camera/DF?t=hero3black&p=%15100GOPRO/GOPR0001.JPG`

so in general it is like

> 10.5.5.9/camera/DF?t=**{password}**&p=%15100GOPRO/**{filename}**

the `100GOPRO` file is always the same (at least in Hero 3) as it is originally comes from `http://10.5.5.9:8080/videos/DCIM/100GOPRO/` Cherokee file browser.

**Comment by smaletho** [comment]
Oh, you're a hero. Thanks so much.
