### ISSUE TITLE
Trying to connect to Hero+LCD but http://bacpac/sd webrequest does not return

### ISSUE THREAD

**Issue by ghost** [r1pper/GoPro.Hero#15]
First off, let me say that your library is really neat, thank you.

I can go to http://bacpac/sd in a browser and I get back a file that downloads.  However the the first WebRequest to the camera hangs.   Is there a tip you might give me to help debug this?

Thank you for any help.
Brett

**Comment by r1pper** [comment]
Hi Brett
thanks and sorry for the late answer
I believe Hero+LCD protocol is based on Hero4 series, at this point the library only supports Hero2/3/3+ cameras, unfortunately I don't own any of the Hero4 series cameras, hence I couldn't add support for the new protocol.

one alternative would be Denis Carriere's nice [library for Hero4 cameras] which(https://github.com/DenisCarriere/gopro) is written in python.

Best regards

**Comment by ghost** [comment]
Thank you so much for the info, I will try it out.
