### ISSUE TITLE
What's your project's license?

### ISSUE THREAD

**Issue by andyp-79** [r1pper/GoPro.Hero#8]
Hi, I was looking to extend my WP8 app, Action Camera, with your media browser. What is your license for your library? I'd be contributing changes back of course, if I end up extending it.

**Comment by KonradIT** [comment]
@andrespetralli you can use the commands, me and other developer are using the files here for our own apps.

**Comment by andyp-79** [comment]
r1pper owns the original code, so I'd like to know what under what terms he would like to share it. You can choose your license on github for each project. Doing so would bring some clarity.

**Comment by KonradIT** [comment]
@andrespetralli BTW, I have a Lumia 520 and your app works amazingly well on hero2 and hero3 black. What lib did you used to preview the gopro m3u8?

**Comment by andyp-79** [comment]
Thanks! I wrote my own HLS decoder from scratch. The WP phone can play H.264. It's just a matter of demuxing the stream. I also saw that there is an open source project for HLS: http://phonesm.codeplex.com . It didn't work last year when I was playing with it due to some bugs, but it might actually be ok now.

**Comment by r1pper** [comment]
@andrespetralli  sorry for the late answer, the repository will be under MIT license so feel free to use it in commercial projects, and we appreciate your contribution

best regards
Hessam

**Comment by r1pper** [comment]
@andrespetralli @KonradIT  added the license to repository so I'm gonna close the issue, thanks for mentioning it.

Best regards
Hessam
